# Generated by Django 4.0.4 on 2022-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('C', 'Completed')], default='N', max_length=1),
        ),
    ]
